# Generated by Django 5.2.7 on 2025-10-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=64)),
                ('summary', models.TextField(blank=True, default='')),
                ('io_signature', models.JSONField(default=dict)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='NodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semver', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('stable', 'stable'), ('beta', 'beta'), ('deprecated', 'deprecated')], default='stable', max_length=16)),
                ('param_schema', models.JSONField(default=dict)),
                ('runtimes', models.JSONField(default=dict)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='registry.node')),
            ],
            options={
                'unique_together': {('node', 'semver')},
            },
        ),
    ]
